version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.4.0
        steps:
            - run: yarn install
            - run: yarn build
            - run: ls
            - run:
            - run: echo "A first hello"
    deploy:
        machine:
            enables: true
        steps:
            - run: Deploy Over SSH
                name: Deploy Over SSH
                command: |
                    rsync -az -vv --delete -e \'ssh -p $SSH_PORT\' build/* $SSH_USER:/data/www/meme/

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - buil
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: master
