defaults:
    working_directory: /tmp

version: 2
jobs:
    build:
        <<:
        docker:
            - image: circleci/node:10.4.0
        steps:
            - run: pwd
            - checkout
            - run: yarn install
            - run: yarn build
            - run: pwd
            - run: mkdir -p meme
            - persist_to_workspace:
                root: meme
                paths:
                    - echo-output
    deploy:
        <<:
        machine:
            enables: true
        steps:
            - attach_workspace:
                at: /tmp/meme
            - run:
                name: Deploy Over SSH
                command: |
                    rsync -az -vv --delete -e ssh build/* $SSH_USER@$SSH_IP:/data/www/meme/

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: master
