version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.4.0
        steps:
            - checkout
            - run: yarn install
            - run: yarn build
            - run: ls
            - run: echo "A first hello"
