version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.4.0
        steps:
            - run:
                name: Update System
                command: |
                    sudo apt-get update && sudo apt-get install rsync
            - checkout
            - run: 
                name: Install Dependence
                command: |
                    yarn install && yarn build
            - run:
                name: Add KnownHosts
                command: |
                    { ssh-keyscan $SSH_IP 2> /dev/null; } >> ~/.ssh/known_hosts
            - deploy:
                name: Deploy via ssh
                command: |
                    if [ ${CIRCLE_BRANCH} = "master" ];then
                        rsync -az -v --delete -e ssh build/* $SSH_USER@$SSH_IP:/data/www/meme/
                    else
                        echo "Not master branch"
                    fi
