defaults:
    working_directory: /home/circleci/project

version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.4.0
        steps:
            - checkout
            - run: yarn install
            - run: yarn build
            - persist_to_workspace:
                root: Meme-generator
                paths:
                    - echo-output
    deploy:
        machine:
            enables: true
        steps:
            - attach_workspace:
                at: /home/circleci/project/Meme-generator
            - run:
                name: Deploy Over SSH
                command: |
                    rsync -az -vv --delete -e ssh build/* $SSH_USER@$SSH_IP:/data/www/meme/

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: master
